name: demo_flutter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: 2.10.5

dependencies:
  bloc: ^8.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

  cupertino_icons: ^1.0.2

  http: ^0.13.4

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  demo_theme:
    path: packages/demo_theme
  demo_ui:
    path: packages/demo_ui
  data:
    path: packages/data
  demo_components:
    path: packages/demo_components



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/components/
    - assets/images/bonus_animation/
    - assets/images/score/
    - assets/images/loading_game/

flutter_gen:
  line_length: 80