name: demo_theme
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^2.4.0

flutter:
  generate: true
  assets:
    - assets/images/
    - assets/images/android/
    - assets/images/dash/
    - assets/images/dino/
    - assets/images/sparky/

flutter_gen:
  assets:
    package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80
  integrations:
    flutter_svg: true

