name: demo_ui
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/dialog/
    - assets/images/button/
  fonts:
    - family: PixeloidSans
      fonts:
        - asset: fonts/PixeloidSans-nR3g1.ttf
        - asset: fonts/PixeloidSansBold-RpeJo.ttf
          weight: 700
    - family: PixeloidMono
      fonts:
        - asset: fonts/PixeloidMono-1G8ae.ttf

flutter_gen:
  line_length: 80
  assets:
    package_parameter_enabled: true
